# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minisky < Formula
  desc "High-fidelity local GCP emulator."
  homepage "https://github.com/qamarudeenm/minisky"
  version "1.0.1"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/qamarudeenm/minisky/releases/download/v1.0.1/minisky_linux_amd64.tar.gz"
    sha256 "b88b7aebc11da7e118ba0bb0044dd858f6e4384b13959d4bd8d6d6a5ae330d5e"
    define_method(:install) do
      bin.install "minisky"
    end
  end

  test do
    system "#{bin}/minisky version"
  end
end
