# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Minisky < Formula
  desc "High-fidelity local GCP emulator."
  homepage "https://github.com/minisky-io/minisky"
  version "1.0.0"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/qamarudeenm/minisky/releases/download/v1.0.0/minisky_linux_amd64.tar.gz"
    sha256 "13567837b8da2be749df00fbb127678c78ed08b9a3d42ac7a97646fdce900c81"
    define_method(:install) do
      bin.install "minisky"
    end
  end

  test do
    system "#{bin}/minisky version"
  end
end
